### ISSUE TITLE
Path of SignerInformation

### ISSUE THREAD

**Issue by nodh** [eu-digital-green-certificates/dgc-lib#20]
Apparently, the Path for `signerInformation` has chaged to `signerCertificate` in the latest release of the Gateway: https://eu-digital-green-certificates.github.io/dgc-gateway/#/

https://github.com/eu-digital-green-certificates/dgc-lib/blob/e0d1592cf218b7cd58a14405e691c019ab1d53c6/src/main/java/eu/europa/ec/dgc/gateway/connector/client/DgcGatewayConnectorRestClient.java#L59

**Comment by f11h** [comment]
Hello @nodh ,

thanks for posting this bug. This is correct!
I've already created a fix for this which was recently merged and is available in 0.4.0 (https://github.com/eu-digital-green-certificates/dgc-lib/releases/tag/0.4.0)
