### ISSUE TITLE
Base45 compliant

### ISSUE THREAD

**Issue by M3kH** [eu-digital-green-certificates/dgc-lib#29]
Is `dgc-lib` encoding and decoding Base45 messages?
Might be my inexperience with the codebase, but I could just see `Base64` encodings.

Isn't one of the requirement of the standard to encode and decode on `Base45`?

**Comment by f11h** [comment]
Hi @M3kH ,

currently the dgc-lib does not support base45 encoding.
Maybe you can have a look over there: https://github.com/ehn-digital-green-development/base45-java

I do not think that it makes sense to clone such a feature into dgc-lib

**Comment by M3kH** [comment]
Thanks @f11h for the clarification.
