### ISSUE TITLE
Valueset/Business Rules Enhancements

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-digital-green-certificates/dgc-lib#36]
The dgc lib should be enhanced to download and verify business rules. The provisioning of valuesets should also be included.

The implementation should be similiar to the TrustListItem e.g. BusinessRulesItem,ValueSetItem, CountryListItem etc.

**Comment by nodh** [comment]
Any chance, that an implementation of `DgcGatewayValidationRuleUploadConnector` will be provided along the download implementations?

**Comment by f11h** [comment]
HI @nodh ,

I've created an issue for that: https://github.com/eu-digital-green-certificates/dgc-lib/issues/55

I think I will be able to add re required connector within this week.
