### ISSUE TITLE
Using as a dependency throws DependencyResolutionException

### ISSUE THREAD

**Issue by towameister** [eu-digital-green-certificates/dgc-lib#43]
## Describe the bug

Trying to use this library as a Maven Dependency leads to Maven not being able to resolve the dependency. Both the POM and JAR download links (https://repo.maven.apache.org/maven2/eu/europa/ec/dgc/dgc-lib/0.5.1/dgc-lib-0.5.1.pom, https://repo.maven.apache.org/maven2/eu/europa/ec/dgc/dgc-lib/0.5.1/dgc-lib-0.5.1.jar) show 404.

## Expected behaviour

Maven should find and download the dependency.

## Steps to reproduce the issue
Included dependency in pom.xml in fresh Spring Boot project according to Usage. 
Updated settings.xml with PAT and username according to settings.xml in source code. 
tried mvnw install.

## Technical details

- Host Machine OS (Windows/Linux/Mac): Windows 10

**Comment by daniel-eder** [comment]
This package is not being published to the Apache maven, but rather to GitHub's (https://maven.pkg.github.com/).

Please make sure to follow https://github.com/eu-digital-green-certificates/dgc-lib#authenticating-to-github-packages to properly authenticate, and that the correct repository is added to your pom.xml

The projects in this organization that use the dgc-lib (such as dgc-gateway) have the repositories set up correctly, a separate project would need to set them up as per https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry.
