### ISSUE TITLE
Error in SignedCertificateMessageBuilder

### ISSUE THREAD

**Issue by Razumain** [eu-digital-green-certificates/dgc-lib#44]
The following code to get the signing algorithm is in error (row 100 and 101):
 
```
String signingAlgorithmName =   
new DefaultAlgorithmNameFinder().getAlgorithmName(signingCertificate.getSignatureAlgorithm());

```
There are 2 problems here

1. The signing algorithm of the private key is NOT necessarily the signing algorithm of the public key certificate. Example I have a public/private EC key pair, but the certificate of the public key is signed by the CA using an RSA key. The code above then attempts to use the EC key with the RSA algorithm used to sign the certificate, which is a complete mismatch.
2. If the signing algorithm is RSA-PSS, then the code above fails. This has to do with RSA-PSS using more complex parameter structure. The code above concludes that the algorithm is simply "RSAPSS" and this results in an exception in the next step.

I have altered this code in my own version of the class to:

```
ASN1ObjectIdentifier publicKeyAlgoOID = 
      signingCertificate.getSubjectPublicKeyInfo().getAlgorithm().getAlgorithm();
String signingAlgorithmName = null;
if (publicKeyAlgoOID.equals(PKCSObjectIdentifiers.rsaEncryption)) signingAlgorithmName = "SHA256WITHRSA";
if (publicKeyAlgoOID.equals(X9ObjectIdentifiers.id_ecPublicKey)) signingAlgorithmName = "SHA256WITHECDSA";
if (signingAlgorithmName == null) throw new RuntimeException("Public key must be RSA or EC");

```

**Comment by f11h** [comment]
Hi @Razumain ,

thanks for reporting this issue. You are totally right. I will add your proposed change to dgc-lib shortly.
