### ISSUE TITLE
DccTestBuilder is missing testIdentifier

### ISSUE THREAD

**Issue by robertjanetzko** [eu-digital-green-certificates/dgc-lib#45]
The `DccTestBuilder` is missing the option to set the now required field `ma` (testIdentifier).

```
    /**
     * test identifier.
     * @param testIdentifier id according to https://github.com/ehn-dcc-development/ehn-dcc-valuesets/blob/main/test-manf.json
     * @return builder
     */
    public DccTestBuilder testIdentifier(String testIdentifier) {
        testObject.set("ma", jsonNodeFactory.textNode(testIdentifier));
        requiredNotSet.remove(RequiredFields.ma);
        return this;
    }
```

**Comment by a-trzewik** [comment]
"ma" is not required regarding schema 1.3.0
https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/main/DCC.combined-schema.json
but indeed there is some logical requirement
https://ec.europa.eu/health/sites/default/files/ehealth/docs/covid-certificate_json_specification_en.pdf
(page 10)
For RAT:exactly 1 (one) non-empty field MUST be provided. 
But it concern only the 1.3.0 schema version

I will add the fields "ma" and "nm" to builder anyway. But no manadatory check (there is no support for different schema versions)
