### ISSUE TITLE
Problem in method DgcGatewayDownloadConnector::updateIfRequired()

### ISSUE THREAD

**Issue by kristank** [eu-digital-green-certificates/dgc-lib#73]
Hello,

I have found the following problem. The line (DgcGatewayDownloadConnector.java, method updateIfRequired, line 105)
```java
trustedCscaCertificateMap = trustedCscaCertificates.stream()
    .collect(Collectors.toMap((ca) -> ca.getSubject().toString(), (ca) -> ca));
```
throws exception `java.lang.IllegalStateException: Duplicate key` if `trustedCscaCertificates`  contains two (or more) certificates 
with same subject. 

I am using [development gateway](https://test-dgcg-ws.tech.ec.europa.eu). The problematic certificates returned by the gateway are 

1. First
    - Subject: C=BB,ST=NRW,L=Test,O=MinistryOfTest,OU=DGCOperations,CN=CSCA_DGC_DE_01
    - SN: 522704455866195600131091134914499111884383337176

2. Second
    - Subject: C=BB,ST=NRW,L=Test,O=MinistryOfTest,OU=DGCOperations,CN=CSCA_DGC_DE_01
    - SN: 579131198531557717335939590388500291603260377746

**Comment by f11h** [comment]
Problem should be fixed with #67
