### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by f11h** [eu-digital-green-certificates/dgc-lib#8]
To ensure reliability on dgc-lib we have to implement a set of Unit Tests.

TODO:
- [x] Message Builder
- [x] Message Parser
- [x] Certificate Converter X509Certificate -> X509CertificateHolder 
- [x] Certificate Converter X509CertificateHolder -> X509Certificate
- [x] Calculate Kid
- [x] Calculate Cert Hash

**Comment by M3kH** [comment]
Hi @f11h i create 2 PR for start implementing testing. Would you be ok to review them?

Anticipated thanks.
